spring:
  application:
    name: user-web
  main:
    allow-bean-definition-overriding: true

server:
  port: 9002

dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848
